using LiteDB;
using QuoteApi.Quotes;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Text;
using QuoteApi.Services;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var geminiApiKey = builder.Configuration["Gemini:ApiKey"];
builder.Services.AddSingleton(new GeminiService(geminiApiKey));

var app = builder.Build();

string dbFile = "quotes.db";

// GET random quote
app.MapGet("/quote", () =>
{
    using var db = new LiteDatabase(dbFile);
    var col = db.GetCollection<Quote>("quotes");
    var count = col.Count();
    if (count == 0)
        return Results.Problem("No quotes available.");
    var random = new Random();
    var skip = random.Next(count);
    var quote = col.Query().Skip(skip).Limit(1).FirstOrDefault();
    return Results.Ok(new { quote = quote?.Text });
});

// POST new quote
app.MapPost("/quote", (QuoteRequest request) =>
{
    if (string.IsNullOrWhiteSpace(request.Quote))
        return Results.BadRequest("Quote cannot be empty.");

    using var db = new LiteDatabase(dbFile);
    var col = db.GetCollection<Quote>("quotes");
    var newQuote = new Quote { Text = request.Quote };
    col.Insert(newQuote);
    return Results.Ok(new { message = "Quote added.", quote = request.Quote });
});

// POST: Add a quote generated by Gemini
app.MapPost("/quote/gemini", async (GeminiService geminiService) =>
{
    var result = await geminiService.GenerateQuoteAsync();

    if (!string.IsNullOrWhiteSpace(result.Error))
        return Results.Problem(result.Error);

    if (string.IsNullOrWhiteSpace(result.Quote))
        return Results.Problem("Gemini API did not return a quote.");

    using var db = new LiteDatabase(dbFile);
    var col = db.GetCollection<Quote>("quotes");
    var newQuote = new Quote { Text = result.Quote };
    col.Insert(newQuote);

    return Results.Ok(new { message = "Gemini quote added.", quote = result.Quote });
});

app.MapGet("/", () => Results.Text("Application is running", "text/html"));

app.Run();
